import React from 'react';

export default function Head() {
  return (
    <>
      <title>About Page</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by Soltis" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}

// copied and updated from head.tsx
// used for updating the head/meta tags on the about page
