export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}

/*
Before: using head.js API
app/head.tsx
export default function Head() {
  return (
    <>
      <title>My Title</title>
    </>
  );
}

After: using Metadata API
app/layout.tsx|page.tsx
export const metadata = {
  title: 'My Title',
}

export default function Layout() {}

*/
